# Generated by Django 6.0.1 on 2026-01-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_link',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
