# Generated by Django 6.0.1 on 2026-01-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(null=True),
        ),
    ]
