# Generated by Django 6.0.1 on 2026-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
