# Generated by Django 6.0.1 on 2026-01-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_experience_internship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
