# Generated by Django 6.0.1 on 2026-01-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Use HTML list tags - li for bullet points'),
        ),
    ]
