# Generated by Django 6.0.1 on 2026-01-25 17:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Use HTML <li> tags for bullet points'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='experience_image'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='internship_image'),
        ),
    ]
